<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17512" started-at="2014-10-28T13:51:36Z" finished-at="2014-10-28T13:51:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17512" started-at="2014-10-28T13:51:36Z" finished-at="2014-10-28T13:51:54Z">
      <class name="TestFolder.TestClass">
        <test-method status="FAIL" signature="testsomething()[pri:0, instance:TestFolder.TestClass@7717cddf]" name="testsomething" duration-ms="16082" started-at="2014-10-28T15:51:36Z" finished-at="2014-10-28T15:51:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Fail URL] 
Expecting:
 <"http://softserve.ua/">
to be equal to:
 <"http://softserve1.ua/">
but was not.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Fail URL] 
Expecting:
 <"http://softserve.ua/">
to be equal to:
 <"http://softserve1.ua/">
but was not.
	at TestFolder.TestClass.testsomething(TestClass.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testsomething -->
      </class> <!-- TestFolder.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
